### ISSUE TITLE
afk_check error

### ISSUE THREAD

**Issue by Z-RAY-Z** [Grey83/SourceMod-plugins#1]
Решил поставить себе afk_check на 
SM 1.9, спамит в консоли:
L 12/27/2018 - 21:31:01: [SM] Blaming: AFK check.smx
L 12/27/2018 - 21:31:01: [SM] Call stack trace:
L 12/27/2018 - 21:31:01: [SM]   [1] Line 77, plugin.sp::Event_Spawn
L 12/27/2018 - 21:31:24: [SM] Exception reported: Array index out-of-bounds (index 315, limit 66)
L 12/27/2018 - 21:31:24: [SM] Blaming: AFK check.smx
L 12/27/2018 - 21:31:24: [SM] Call stack trace:
L 12/27/2018 - 21:31:24: [SM]   [1] Line 77, plugin.sp::Event_Spawn
L 12/27/2018 - 21:31:24: [SM]   [3] CS_RespawnPlayer
L 12/27/2018 - 21:31:24: [SM]   [4] Line 98, C:\Users\inkle\Desktop\Новая папка 22\PRIVATE\rpg_fix_by_1mpulse\modules_for_smrpg\sm\smrpg_respawn.sp::Timer_Respawn
L 12/27/2018 - 21:32:42: [SM] Exception reported: Array index out-of-bounds (index 316, limit 66)
L 12/27/2018 - 21:32:42: [SM] Blaming: AFK check.smx
L 12/27/2018 - 21:32:42: [SM] Call stack trace:
L 12/27/2018 - 21:32:42: [SM]   [1] Line 77, plugin.sp::Event_Spawn
[errors_20181227.log](https://github.com/Grey83/SourceMod-plugins/files/2713079/errors_20181227.log)

**Comment by Grey83** [comment]
**bNew[event.GetInt("userid")] = false;**
== >
**bNew[GetClientOfUserId(event.GetInt("userid"))] = false;**

[исправлено](https://github.com/Grey83/SourceMod-plugins/commit/c14523eed132a1bde8f9b26077e4d3c423a1abe0#diff-9430dd4982b6f8474f4ceaf7fa2f4fafL77)
